# ======================================================
#  rEFInd Configuration - Laptop Internal & External Arch
# ======================================================

resolution 1920 1080

scanfor internal,external

# Oculta entradas duplicadas, fallbacks e refind de segurança do arch externo
dont_scan_files bootx64.efi, systemd-bootx64.efi, initramfs-linux-fallback.img
dont_scan_dirs /EFI/boot, /EFI/systemd, /EFI/arch, /EFI/refind
